jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event: ${{ github.event_name }}"
          echo "branch ${{ github.ref }}"
      - uses: actions/checkout@v3.3.0
      - name: List files in the repository
        run: |
          echo "repository: ${{ github.repository }} contains files:"
          tree
